# Generated by Django 4.2.5 on 2023-09-17 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='models2',
            old_name='deta2',
            new_name='data2',
        ),
        migrations.AddField(
            model_name='models2',
            name='user2',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
