# Generated by Django 4.2.5 on 2023-09-17 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0002_rename_deta2_models2_data2_models2_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models2',
            name='user2',
        ),
        migrations.AddField(
            model_name='models2',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
