# Generated by Django 4.2.5 on 2023-09-17 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_models2_user2_models2_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models2',
            name='data2',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
