# Generated by Django 4.2.5 on 2023-09-16 19:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_alter_models1_deta'),
    ]

    operations = [
        migrations.AddField(
            model_name='models1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='models1',
            name='deta',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='models1',
            name='lastname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='models1',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
