# Generated by Django 4.2.5 on 2023-09-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_models1_user_alter_models1_deta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models1',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='models1',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
